name: Count Lines of Code
on: workflow_dispatch
jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count Lines of Code
        uses: djdefi/cloc-action@5
